server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: user
    password: password
    hikari:
      maximum-pool-size: 5
      connection-timeout: 2000 #ms

  config:
    import: "" # When using Config Service, add "optional:configserver:"
  cloud:
    config:
      enabled: false # When using Config Service, set to true
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1

  profiles:
    active: test-data

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, heapdump, info, loggers, mappings, prometheus, refresh
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

polar:
  greeting: Welcome to the local book catalog!